import { Language } from '../i18n/translations';
import { Order, User } from '../types';

export type BuyerAccountTab = 'overview' | 'profile' | 'orders' | 'coupons' | 'settings' | 'addresses' | 'payments' | 'disputes' | 'security';

const tabs: Array<{ id: BuyerAccountTab; label: string; icon: string; group?: string }> = [
  { id: 'overview', label: 'Account overview', icon: 'fa-grid-2' },
  { id: 'profile', label: 'Profile & personalization', icon: 'fa-user-pen', group: 'Your account' },
  { id: 'orders', label: 'My orders & tracking', icon: 'fa-box-open', group: 'Your account' },
  { id: 'coupons', label: 'My coupons', icon: 'fa-ticket' },
  { id: 'addresses', label: 'Saved addresses', icon: 'fa-location-dot' },
  { id: 'payments', label: 'Payment methods', icon: 'fa-wallet' },
  { id: 'disputes', label: 'Refunds & disputes', icon: 'fa-rotate-left' },
  { id: 'settings', label: 'Account settings', icon: 'fa-sliders', group: 'Preferences' },
  { id: 'security', label: 'Security', icon: 'fa-shield-halved' }
];

function tabButton(tab: typeof tabs[number], activeTab: BuyerAccountTab): string {
  return `<button onclick="window.setBuyerAccountTab('${tab.id}')" class="account-nav-item ${activeTab === tab.id ? 'active' : ''}">
    <i class="fa-solid ${tab.icon} w-5 text-center"></i><span>${tab.label}</span>
  </button>`;
}

function renderOverview(user: User, orders: Order[]): string {
  const activeOrders = orders.filter(order => !['delivered', 'cancelled'].includes(order.status));
  const delivered = orders.filter(order => order.status === 'delivered').length;
  return `<div class="space-y-6 animate-fade-in">
    <div class="account-welcome">
      <div><p class="account-kicker">BUYER ACCOUNT</p><h1>Good morning, ${user.name.split(' ')[0]}</h1><p>Everything you need to source, receive, and manage your produce orders.</p></div>
      <button onclick="window.navigateTab('marketplace')" class="btn-primary"><i class="fa-solid fa-store"></i> Browse marketplace</button>
    </div>
    <div class="account-stat-grid">
      <div class="account-stat"><span class="stat-icon green"><i class="fa-solid fa-box"></i></span><div><strong>${activeOrders.length}</strong><span>Active orders</span></div></div>
      <div class="account-stat"><span class="stat-icon blue"><i class="fa-solid fa-truck-fast"></i></span><div><strong>${orders.filter(o => o.status === 'picked_up').length}</strong><span>In transit</span></div></div>
      <div class="account-stat"><span class="stat-icon gold"><i class="fa-solid fa-circle-check"></i></span><div><strong>${delivered}</strong><span>Delivered</span></div></div>
      <div class="account-stat"><span class="stat-icon rose"><i class="fa-solid fa-ticket"></i></span><div><strong>3</strong><span>Available coupons</span></div></div>
    </div>
    <section class="account-section"><div class="section-heading"><div><p class="account-kicker">RECENT ACTIVITY</p><h2>Orders at a glance</h2></div><button onclick="window.setBuyerAccountTab('orders')" class="text-action">View all <i class="fa-solid fa-arrow-right"></i></button></div>
      ${orders.length ? `<div class="account-list">${orders.slice(0, 3).map(order => `<div class="order-row"><div class="order-product"><span class="order-thumb"><i class="fa-solid fa-wheat-awn"></i></span><div><strong>${order.productName}</strong><small>Order #${order.id.slice(0, 8).toUpperCase()} · ${order.qtyKg} kg · ${order.farmerName}</small></div></div><span class="badge-status status-${order.status}">${order.status.replace('_', ' ')}</span><strong class="order-price">${order.totalEtb.toLocaleString()} ETB</strong></div>`).join('')}</div>` : `<div class="empty-account"><i class="fa-solid fa-box-open"></i><p>No orders yet</p><button onclick="window.navigateTab('marketplace')" class="text-action">Find fresh produce</button></div>`}
    </section>
  </div>`;
}

function renderProfile(user: User): string {
  return `<div class="space-y-6 animate-fade-in"><div class="account-page-title"><p class="account-kicker">YOUR ACCOUNT</p><h1>Profile & personalization</h1><p>Keep your identity and delivery preferences up to date.</p></div>
    <section class="account-section"><div class="profile-header"><div class="avatar-large">${user.name.charAt(0).toUpperCase()}</div><div><h2>${user.name}</h2><p>${user.phone} · ${user.region || 'Ethiopia'}</p></div><button class="btn-secondary ml-auto" onclick="window.showAccountToast('Avatar upload is ready for blob storage integration.','fa-image')"><i class="fa-solid fa-camera"></i> Change photo</button></div>
      <form onsubmit="event.preventDefault(); window.saveBuyerProfile()" class="account-form"><label>Full name<input name="name" value="${user.name}" required /></label><label>Amharic name<input name="nameAm" value="${user.nameAm || ''}" placeholder="Optional" /></label><label>Region<input name="region" value="${user.region || 'Addis Ababa'}" required /></label><label>Email<input type="email" name="email" value="${user.email || ''}" placeholder="Optional" /></label><label>Preferred currency<select name="currency"><option>ETB - Ethiopian Birr</option><option>USD - US Dollar</option><option>EUR - Euro</option></select></label><label>Preferred language<select name="languagePreference"><option value="en" ${user.languagePreference === 'en' ? 'selected' : ''}>English</option><option value="am" ${user.languagePreference === 'am' ? 'selected' : ''}>Amharic</option></select></label>
        <div class="form-wide location-field"><div><span class="field-label">Default delivery address</span><input name="savedDeliveryAddress" value="${user.savedDeliveryAddress || ''}" placeholder="Street, city, region" /><p>Order locations are captured separately at checkout.</p></div><button type="button" class="btn-secondary" onclick="window.captureBuyerLocation()"><i class="fa-solid fa-location-crosshairs"></i> Use current location</button></div><div class="form-wide flex justify-end"><button class="btn-primary" type="submit"><i class="fa-solid fa-check"></i> Save changes</button></div></form>
    </section></div>`;
}

function renderOrders(orders: Order[]): string {
  return `<div class="space-y-6 animate-fade-in"><div class="account-page-title"><p class="account-kicker">PURCHASE HISTORY</p><h1>My orders & shipping</h1><p>Track every delivery from farmer confirmation to your doorstep.</p></div><div class="account-tabs"><button class="selected">All <b>${orders.length}</b></button><button>To pay <b>0</b></button><button>In transit <b>${orders.filter(o => ['confirmed', 'picked_up'].includes(o.status)).length}</b></button><button>Delivered <b>${orders.filter(o => o.status === 'delivered').length}</b></button><button>Disputed <b>${orders.filter(o => o.status === 'disputed').length}</b></button></div><section class="account-section"><div class="account-list">${orders.length ? orders.map(order => `<div class="order-card"><div class="order-row"><div class="order-product"><span class="order-thumb"><i class="fa-solid fa-carrot"></i></span><div><strong>${order.productName}</strong><small>Order #${order.id.slice(0, 8).toUpperCase()} · Farmer: ${order.farmerName}</small></div></div><span class="badge-status status-${order.status}">${order.status.replace('_', ' ')}</span></div><div class="tracking-line"><span class="done"><i class="fa-solid fa-check"></i> Order placed</span><span class="${['confirmed', 'picked_up', 'delivered'].includes(order.status) ? 'done' : ''}"><i class="fa-solid fa-check"></i> Farmer confirmed</span><span class="${['picked_up', 'delivered'].includes(order.status) ? 'done' : ''}"><i class="fa-solid fa-truck"></i> In transit</span><span class="${order.status === 'delivered' ? 'done' : ''}"><i class="fa-solid fa-house"></i> Delivered</span></div><div class="order-footer"><span>${order.qtyKg} kg · ${order.totalEtb.toLocaleString()} ETB</span><span>Payment: ${order.paymentRef || 'Telebirr escrow'}</span><button class="text-action" onclick="window.showAccountToast('Live driver location will appear here when assigned.','fa-map-location-dot')">Track delivery <i class="fa-solid fa-arrow-right"></i></button></div></div>`).join('') : '<div class="empty-account"><i class="fa-solid fa-box-open"></i><p>Your order history will appear here.</p></div>'}</div></section></div>`;
}

function renderSimpleModule(tab: BuyerAccountTab, orders: Order[], accountData: { addresses: any[]; paymentMethods: any[]; coupons: any[]; notificationPreferences: any[]; sessions: any[]; twoFactor: any }): string {
  if (tab === 'addresses') return renderAddresses(accountData.addresses);
  if (tab === 'payments') return renderPayments(accountData.paymentMethods);
  if (tab === 'disputes') return renderDisputes(orders);
  const content: Record<string, { kicker: string; title: string; description: string; icon: string; rows: string[] }> = {
    coupons: { kicker: 'SAVINGS', title: 'My coupons', description: 'Use platform, farmer, and referral rewards at checkout.', icon: 'fa-ticket', rows: accountData.coupons.length ? accountData.coupons.map(coupon => `${coupon.code} · ${coupon.value}${coupon.discountType === 'Percent' ? '%' : ' ETB'} · Expires ${new Date(coupon.expiresAt).toLocaleDateString()}`) : ['No coupons are currently available · Coupons will appear here when issued by the platform or a farmer'] },
    addresses: { kicker: 'DELIVERY', title: 'Saved addresses', description: 'Manage shipping destinations with flexible Ethiopian address details.', icon: 'fa-location-dot', rows: accountData.addresses.length ? accountData.addresses.map(address => `${address.name} · ${address.street}, ${address.city}, ${address.region}${address.isDefaultShipping ? ' · Default shipping' : ''}`) : ['No saved addresses yet · Add your first address to speed up checkout'] },
    payments: { kicker: 'CHECKOUT', title: 'Payment methods', description: 'Payment details stay with Telebirr or Chapa. This account shows references attached to your orders.', icon: 'fa-wallet', rows: accountData.paymentMethods.length ? accountData.paymentMethods.map(method => `${method.provider} · ${method.maskedDisplay || 'Provider token linked'}${method.isPrimary ? ' · Primary' : ''}`) : (orders.length ? orders.map(order => `${order.paymentRef || 'Payment reference pending'} · Order #${order.id.slice(0, 8).toUpperCase()} · ${order.totalEtb.toLocaleString()} ETB`) : ['No payment methods are linked yet']) },
    disputes: { kicker: 'RESOLUTION CENTER', title: 'Refunds & disputes', description: 'Open a case for an order that was damaged, missing, wrong, or below quality.', icon: 'fa-rotate-left', rows: orders.filter(order => order.status === 'disputed').length ? orders.filter(order => order.status === 'disputed').map(order => `${order.productName} · Order #${order.id.slice(0, 8).toUpperCase()} · ${order.disputeStatus || 'Under review'}`) : ['No open disputes · Refunds return through the original Telebirr or Chapa method', 'Dispute window: 3 days after delivery · Proof supports up to 5 images and 1 video'] },
    settings: { kicker: 'PREFERENCES', title: 'Account settings', description: 'Choose how Farmer-to-Market keeps you informed and how your data is used.', icon: 'fa-sliders', rows: accountData.notificationPreferences.length ? accountData.notificationPreferences.map(preference => `${preference.eventType} · SMS ${preference.smsEnabled ? 'on' : 'off'} · In-app ${preference.inAppEnabled ? 'on' : 'off'}`) : ['No notification preferences saved yet · Defaults are applied by the server'] },
    security: { kicker: 'PROTECTION', title: 'Security', description: 'Keep your account protected with password, two-factor authentication, and session controls.', icon: 'fa-shield-halved', rows: ['Password · Change it through the form below', `Two-factor authentication · ${accountData.twoFactor?.isEnabled ? `${accountData.twoFactor.method} enabled` : 'Not enabled'}`, `Active sessions · ${accountData.sessions.length} active session${accountData.sessions.length === 1 ? '' : 's'}`] }
  };
  const item = content[tab];
  const passwordForm = tab === 'security' ? `<form onsubmit="event.preventDefault(); window.changeBuyerPassword()" class="account-form mt-6"><label>Current password<input type="password" name="currentPassword" required /></label><label>New password<input type="password" name="newPassword" minlength="8" required /></label><div class="form-wide flex justify-end"><button class="btn-primary" type="submit"><i class="fa-solid fa-key"></i> Change password</button></div></form><button class="btn-secondary mt-4" onclick="window.revokeBuyerSessions()"><i class="fa-solid fa-right-from-bracket"></i> Log out all other sessions</button>` : '';
  return `<div class="space-y-6 animate-fade-in"><div class="account-page-title"><p class="account-kicker">${item.kicker}</p><h1>${item.title}</h1><p>${item.description}</p></div><section class="account-section"><div class="module-list">${item.rows.map(row => `<div class="module-row"><span class="module-icon"><i class="fa-solid ${item.icon}"></i></span><div><strong>${row.split(' · ')[0]}</strong><p>${row.split(' · ').slice(1).join(' · ') || 'Ready to configure'}</p></div></div>`).join('')}</div>${passwordForm}</section></div>`;
}

function renderAddresses(addresses: any[]): string {
  return `<div class="space-y-6 animate-fade-in"><div class="account-page-title"><p class="account-kicker">DELIVERY</p><h1>Saved addresses</h1><p>Manage shipping destinations. Postal codes remain optional.</p></div><section class="account-section"><div class="module-list">${addresses.length ? addresses.map(address => `<div class="module-row"><span class="module-icon"><i class="fa-solid fa-location-dot"></i></span><div><strong>${address.name} ${address.isDefaultShipping ? '<em class="account-badge">Default shipping</em>' : ''}</strong><p>${address.street}, ${address.city}, ${address.region}, ${address.country}<br>${address.phone}${address.postalCode ? ` · ${address.postalCode}` : ''}</p></div><button class="icon-button" title="Delete address" onclick="window.deleteBuyerAddress('${address.id}')"><i class="fa-solid fa-trash"></i></button></div>`).join('') : '<div class="empty-account"><i class="fa-solid fa-location-dot"></i><p>No saved addresses yet.</p></div>'}</div><form onsubmit="event.preventDefault(); window.addBuyerAddress()" class="account-form mt-6"><label>Address name<input name="name" placeholder="Wholesale hub" required></label><label>Phone<input name="phone" placeholder="+251 9•• ••• •••" required></label><label>Street<input name="street" required></label><label>City<input name="city" required></label><label>Region<input name="region" required></label><label>Postal code<input name="postalCode" placeholder="Optional"></label><label>Country<input name="country" value="Ethiopia" required></label><label class="flex items-center gap-2"><input type="checkbox" name="isDefaultShipping"> Default shipping</label><div class="form-wide flex justify-end"><button class="btn-primary" type="submit"><i class="fa-solid fa-plus"></i> Add address</button></div></form></section></div>`;
}

function renderPayments(methods: any[]): string {
  return `<div class="space-y-6 animate-fade-in"><div class="account-page-title"><p class="account-kicker">CHECKOUT</p><h1>Payment methods</h1><p>Use Telebirr or Chapa hosted tokenization. Raw card numbers never reach this app.</p></div><section class="account-section"><div class="module-list">${methods.length ? methods.map(method => `<div class="module-row"><span class="module-icon"><i class="fa-solid ${method.provider === 'Telebirr' ? 'fa-mobile-screen-button' : 'fa-credit-card'}"></i></span><div><strong>${method.provider} ${method.isPrimary ? '<em class="account-badge">Primary</em>' : ''}</strong><p>${method.maskedDisplay || 'Provider token linked'}${method.brand ? ` · ${method.brand}` : ''}</p></div>${method.isPrimary ? '' : `<button class="icon-button" title="Set primary" onclick="window.setPrimaryBuyerPayment('${method.id}')"><i class="fa-solid fa-star"></i></button>`}<button class="icon-button" title="Remove payment method" onclick="window.deleteBuyerPayment('${method.id}')"><i class="fa-solid fa-trash"></i></button></div>`).join('') : '<div class="empty-account"><i class="fa-solid fa-wallet"></i><p>No payment methods linked yet.</p></div>'}</div><form onsubmit="event.preventDefault(); window.addBuyerPayment()" class="account-form mt-6"><label>Provider<select name="provider"><option>Telebirr</option><option>Chapa</option></select></label><label>Provider token<input name="providerToken" placeholder="Paste hosted-provider token" required></label><label>Masked display<input name="maskedDisplay" placeholder="•••• 4242" required></label><label>Brand<input name="brand" placeholder="Visa / Telebirr"></label><label>Expiry month<input type="number" name="expiryMonth" min="1" max="12"></label><label>Expiry year<input type="number" name="expiryYear" min="2026"></label><label class="flex items-center gap-2"><input type="checkbox" name="isPrimary"> Set as primary</label><div class="form-wide flex justify-end"><button class="btn-primary" type="submit"><i class="fa-solid fa-link"></i> Link payment method</button></div></form></section></div>`;
}

function renderDisputes(orders: Order[]): string {
  const eligible = orders.filter(order => order.status === 'delivered' || order.status === 'disputed' || order.disputeStatus?.startsWith('Resolved'));
  return `<div class="space-y-6 animate-fade-in"><div class="account-page-title"><p class="account-kicker">RESOLUTION CENTER</p><h1>Refunds & disputes</h1><p>Submit a claim for a delivered order. Refunds return through the original payment provider.</p></div><section class="account-section"><div class="module-list">${eligible.length ? eligible.map(order => `<div class="module-row"><span class="module-icon"><i class="fa-solid ${order.disputeStatus === 'ResolvedRefundBuyer' ? 'fa-money-bill-transfer' : 'fa-box-open'}"></i></span><div><strong>${order.productName}</strong><p>Order #${order.id.slice(0, 8).toUpperCase()} · ${order.disputeStatus === 'ResolvedRefundBuyer' ? 'Refunded to original payment method' : order.disputeStatus || (order.status === 'disputed' ? 'Under review' : 'Eligible for dispute')}</p></div>${order.status === 'delivered' && !order.disputeStatus?.startsWith('Resolved') ? `<button class="btn-secondary" onclick="window.submitBuyerDispute('${order.id}')"><i class="fa-solid fa-flag"></i> Open dispute</button>` : ''}</div>`).join('') : '<div class="empty-account"><i class="fa-solid fa-circle-check"></i><p>No delivered orders are currently eligible for a dispute.</p></div>'}</div></section></div>`;
}

export function renderBuyerAccountView(lang: Language, user: User, orders: Order[], activeTab: BuyerAccountTab, accountData: { addresses: any[]; paymentMethods: any[]; coupons: any[]; notificationPreferences: any[]; sessions: any[]; twoFactor: any }): string {
  const tab = tabs.find(item => item.id === activeTab) || tabs[0];
  let content = activeTab === 'overview' ? renderOverview(user, orders) : activeTab === 'profile' ? renderProfile(user) : activeTab === 'orders' ? renderOrders(orders) : renderSimpleModule(activeTab, orders, accountData);
  return `<div class="buyer-account-layout"><aside class="account-sidebar"><div class="account-sidebar-profile"><div class="avatar-medium">${user.name.charAt(0).toUpperCase()}</div><div><strong>${user.name}</strong><span>${user.phone}</span></div></div><div class="account-nav">${tabs.map((item, index) => `${item.group && (index === 0 || tabs[index - 1].group !== item.group) ? `<p class="account-nav-group">${item.group}</p>` : ''}${tabButton(item, activeTab)}`).join('')}</div><div class="account-sidebar-help"><i class="fa-solid fa-headset"></i><strong>Need a hand?</strong><span>Visit the Help Center</span><button onclick="window.showAccountToast('Help Center CMS content will open here.','fa-circle-question')">Get help <i class="fa-solid fa-arrow-right"></i></button></div></aside><main class="account-content"><div class="account-breadcrumb"><button onclick="window.navigateTab('marketplace')">Marketplace</button><i class="fa-solid fa-chevron-right"></i><span>${tab.label}</span></div>${content}</main></div>`;
}
