import { Language } from '../i18n/translations';
import { Listing, Order, User } from '../types';
import { PriceBenchmark } from '../types';
import { renderCreateListingModal } from './FarmerView';
import { api } from '../services/api';

export type FarmerAccountTab = 'overview' | 'profile' | 'orders' | 'coupons' | 'addresses' | 'payments' | 'disputes' | 'settings' | 'security';

const tabs: Array<{ id: FarmerAccountTab; label: string; icon: string; group?: string }> = [
  { id: 'overview', label: 'Account overview', icon: 'fa-grid-2' },
  { id: 'profile', label: 'Profile & personalization', icon: 'fa-user-pen', group: 'Your account' },
  { id: 'orders', label: 'My orders & tracking', icon: 'fa-box-open', group: 'Your account' },
  { id: 'coupons', label: 'My coupons', icon: 'fa-ticket' },
  { id: 'addresses', label: 'Saved addresses', icon: 'fa-location-dot' },
  { id: 'payments', label: 'Payment methods', icon: 'fa-wallet' },
  { id: 'disputes', label: 'Refunds & disputes', icon: 'fa-rotate-left' },
  { id: 'settings', label: 'Account settings', icon: 'fa-sliders', group: 'Preferences' },
  { id: 'security', label: 'Security', icon: 'fa-shield-halved' }
];

function navItem(tab: typeof tabs[number], active: FarmerAccountTab): string {
  return `<button onclick="window.setFarmerAccountTab('${tab.id}')" class="account-nav-item ${active === tab.id ? 'active' : ''}"><i class="fa-solid ${tab.icon} w-5 text-center"></i><span>${tab.label}</span></button>`;
}

function renderListings(listings: Listing[]): string {
  return `<section class="account-section"><div class="section-heading"><div><p class="account-kicker">SELLER CENTER</p><h2>My produce posts</h2></div><button class="btn-primary" onclick="window.toggleCreateListingModal()"><i class="fa-solid fa-plus"></i> Post produce</button></div><div class="module-list mt-5">${listings.length ? listings.map(listing => `<div class="module-row"><span class="order-thumb"><img src="${listing.photos[0]}" alt="${listing.productName}" class="w-full h-full object-cover rounded-lg"></span><div><strong>${listing.productName}</strong><p>${listing.qtyKg.toLocaleString()} kg available · ${listing.pricePerKg} ETB/kg · ${listing.status}</p></div><button class="icon-button" title="Delete post" onclick="window.deleteFarmerListing('${listing.id}')"><i class="fa-solid fa-trash text-rose-600"></i></button></div>`).join('') : '<div class="empty-account"><i class="fa-solid fa-seedling"></i><p>You have no active produce posts.</p></div>'}</div></section>`;
}

function renderFarmerModule(tab: FarmerAccountTab, user: User, orders: Order[]): string {
  const openDisputes = orders.filter(order => order.status === 'disputed' || order.disputeStatus?.startsWith('Resolved'));
  if (tab === 'profile') return `<div class="space-y-6 animate-fade-in"><div class="account-page-title"><p class="account-kicker">YOUR FARM ACCOUNT</p><h1>Profile & personalization</h1><p>Update the public identity buyers see and your farm operating region.</p></div><section class="account-section"><div class="profile-header"><div class="avatar-large">${user.name.charAt(0).toUpperCase()}</div><div><h2>${user.name}</h2><p>${user.phone} · ${user.region}</p></div><span class="account-badge">${user.verified ? 'Verified farmer' : 'Verification pending'}</span></div><form onsubmit="event.preventDefault(); window.saveFarmerProfile()" class="account-form"><label>Full name<input name="name" value="${user.name}" required></label><label>Amharic name<input name="nameAm" value="${user.nameAm || ''}" placeholder="Optional"></label><label>Farm region<input name="region" value="${user.region || ''}" required></label><label>Email<input type="email" name="email" value="${user.email || ''}" placeholder="Optional"></label><label>Preferred language<select name="languagePreference"><option value="en" ${user.languagePreference === 'en' ? 'selected' : ''}>English</option><option value="am" ${user.languagePreference === 'am' ? 'selected' : ''}>Amharic</option></select></label><label>Primary produce<input name="primaryCrop" value="${user.primaryCrop || ''}" placeholder="Tomatoes, teff, coffee"></label><div class="form-wide location-field"><div><span class="field-label">Farm pickup address</span><input name="savedDeliveryAddress" value="${user.savedDeliveryAddress || ''}" placeholder="Woreda, kebele, pickup details"><p>Buyers and drivers use this as the default farm location.</p></div><button type="button" class="btn-secondary" onclick="window.captureFarmerLocation()"><i class="fa-solid fa-location-crosshairs"></i> Capture location</button></div><div class="form-wide flex justify-end"><button class="btn-primary" type="submit"><i class="fa-solid fa-check"></i> Save profile</button></div></form></section></div>`;
  const content: Record<string, { kicker: string; title: string; description: string; icon: string; rows: string[] }> = {
    orders: { kicker: 'FULFILLMENT', title: 'Orders & tracking', description: 'Orders appear here after buyers pay. Confirm them so available drivers can pick them up.', icon: 'fa-box-open', rows: orders.length ? orders.map(order => `${order.productName} · ${order.qtyKg} kg · ${order.status.replace('_', ' ')}`) : ['No buyer orders yet'] },
    coupons: { kicker: 'SELLER SAVINGS', title: 'My coupons', description: 'Farmer-issued coupon management will use your payout share.', icon: 'fa-ticket', rows: ['No farmer-issued coupons yet · Coupon creation API is ready for the next seller release'] },
    addresses: { kicker: 'FARM LOCATION', title: 'Saved addresses', description: 'Manage farm pickup locations and operating regions.', icon: 'fa-location-dot', rows: [`${user.region} · Farm pickup region`, 'Additional pickup-address management is pending the farm-location API'] },
    payments: { kicker: 'PAYOUTS', title: 'Payment methods', description: `Manage the Telebirr payout destination for your ${api.getPlatformConfig().farmerSharePercent}% settlement.`, icon: 'fa-wallet', rows: [`Telebirr payout · ${user.phone} · ${api.getPlatformConfig().farmerSharePercent}% farmer share`, 'Bank fallback · Not configured'] },
    disputes: { kicker: 'RESOLUTION CENTER', title: 'Refunds & disputes', description: 'Respond to buyer claims and track payout impact.', icon: 'fa-rotate-left', rows: openDisputes.length ? openDisputes.map(order => `${order.productName} · Order #${order.id.slice(0, 8).toUpperCase()} · ${order.disputeStatus === 'ResolvedRefundBuyer' ? 'Refunded to buyer' : order.disputeStatus || 'Under review'}`) : ['No buyer disputes'] },
    settings: { kicker: 'PREFERENCES', title: 'Account settings', description: 'Configure seller notifications and auto-accept preferences.', icon: 'fa-sliders', rows: ['Order updates · In-app notifications on', 'Dispute updates · SMS on', 'Auto-accept orders · Configure quantity threshold'] },
    security: { kicker: 'PROTECTION', title: 'Security', description: 'Protect your farmer account with password and session controls.', icon: 'fa-shield-halved', rows: ['Password · Change it through the security form', 'Two-factor authentication · SMS recommended', 'Active sessions · Manage from the security API'] }
  };
  const item = content[tab];
  const password = tab === 'security' ? `<form onsubmit="event.preventDefault(); window.changeFarmerPassword()" class="account-form mt-6"><label>Current password<input type="password" name="currentPassword" required></label><label>New password<input type="password" name="newPassword" minlength="8" required></label><div class="form-wide flex justify-end"><button class="btn-primary" type="submit"><i class="fa-solid fa-key"></i> Change password</button></div></form>` : '';
  return `<div class="space-y-6 animate-fade-in"><div class="account-page-title"><p class="account-kicker">${item.kicker}</p><h1>${item.title}</h1><p>${item.description}</p></div><section class="account-section"><div class="module-list">${item.rows.map((row, index) => `<div class="module-row"><span class="module-icon"><i class="fa-solid ${item.icon}"></i></span><div><strong>${row.split(' · ')[0]}</strong><p>${row.split(' · ').slice(1).join(' · ') || 'Ready to configure'}</p></div>${tab === 'orders' && orders[index]?.status === 'pending' ? `<button class="btn-secondary" onclick="window.confirmFarmerOrder('${orders[index].id}')"><i class="fa-solid fa-check"></i> Confirm</button>` : ''}</div>`).join('')}</div>${password}</section></div>`;
}

export function renderFarmerAccountView(lang: Language, user: User, listings: Listing[], orders: Order[], activeTab: FarmerAccountTab, isCreateModalOpen = false, benchmarks: PriceBenchmark[] = []): string {
  const tab = tabs.find(item => item.id === activeTab) || tabs[0];
  const content = activeTab === 'overview' ? `<div class="space-y-6 animate-fade-in"><div class="account-welcome"><div><p class="account-kicker">FARMER ACCOUNT</p><h1>Welcome back, ${user.name.split(' ')[0]}</h1><p>Manage your produce posts, buyer orders, and payouts.</p></div><button class="btn-primary" onclick="window.toggleCreateListingModal()"><i class="fa-solid fa-plus"></i> Post produce</button></div><div class="account-stat-grid"><div class="account-stat"><span class="stat-icon green"><i class="fa-solid fa-seedling"></i></span><div><strong>${listings.length}</strong><span>Active posts</span></div></div><div class="account-stat"><span class="stat-icon blue"><i class="fa-solid fa-box"></i></span><div><strong>${orders.filter(order => order.status === 'pending').length}</strong><span>New orders</span></div></div><div class="account-stat"><span class="stat-icon gold"><i class="fa-solid fa-truck"></i></span><div><strong>${orders.filter(order => order.status === 'picked_up').length}</strong><span>In transit</span></div></div><div class="account-stat"><span class="stat-icon rose"><i class="fa-solid fa-hand-holding-dollar"></i></span><div><strong>${(user.walletBalanceEtb || 0).toLocaleString()}</strong><span>Wallet ETB</span></div></div></div>${renderListings(listings)}</div>` : activeTab === 'profile' ? renderFarmerModule('profile', user, orders) : activeTab === 'orders' ? renderFarmerModule('orders', user, orders) : renderFarmerModule(activeTab, user, orders);
  return `<div class="buyer-account-layout"><aside class="account-sidebar"><div class="account-sidebar-profile"><div class="avatar-medium">${user.name.charAt(0).toUpperCase()}</div><div><strong>${user.name}</strong><span>${user.phone}</span></div></div><div class="account-nav">${tabs.map((item, index) => `${item.group && (index === 0 || tabs[index - 1].group !== item.group) ? `<p class="account-nav-group">${item.group}</p>` : ''}${navItem(item, activeTab)}`).join('')}</div><div class="account-sidebar-help"><i class="fa-solid fa-headset"></i><strong>Farmer support</strong><span>Get help with orders and payouts</span><button onclick="window.showAccountToast('Support center integration is available from the farmer portal.','fa-circle-question')">Get help <i class="fa-solid fa-arrow-right"></i></button></div></aside><main class="account-content"><div class="account-breadcrumb"><button onclick="window.navigateTab('farmer')">Farmer dashboard</button><i class="fa-solid fa-chevron-right"></i><span>${tab.label}</span></div>${content}</main>${isCreateModalOpen ? renderCreateListingModal(lang, benchmarks) : ''}</div>`;
}
